name: Restyled

on:
  push:
    paths:
      - '**/*.js'
      - '**/*.ts'
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'

jobs:
  restyled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.sha }}

      - name: Install Restyled CLI
        uses: restyled-io/actions/setup@v3

      - name: Run Restyled
        id: restyler
        uses: restyled-io/actions/run@v3
        with:
          fail-on-differences: true

      - name: Create Pull Request for Style Fixes
        if: ${{ !cancelled() && steps.restyler.outputs.success == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ steps.restyler.outputs.restyled-base }}
          branch: ${{ steps.restyler.outputs.restyled-head }}
          title: ${{ steps.restyler.outputs.restyled-title }}
          body: ${{ steps.restyler.outputs.restyled-body }}
